question_data =[[{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "The first computer bug was formed by faulty wires.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "text": "Linus Torvalds created Linux and Git.", "answer": "True",
      "inanswers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "&quot;Windows NT&quot; is a monolithic kernel.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
      "answer": "True", "inanswers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "text": "Ada Lovelace is often considered the first computer programmer.",
      "answer": "True", "inanswers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "MacOS is based on Linux.", "answer": "False",
      "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "The open source program Redis is a relational database server.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
      "answer": "True", "inanswers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "text": "The Windows 7 operating system has six main editions.",
      "answer": "True", "inanswers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "The first dual-core CPU was the Intel Pentium D.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "text": "Linux was first created as an alternative to Windows XP.",
      "answer": "False", "inanswers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "text": "Android versions are named in alphabetical order.",
      "answer": "True", "inanswers": ["False"]}]]
